name: Sincronizar Bascula Wyze

on:
  # Se elimina 'schedule' para evitar ejecuciones automáticas
  workflow_dispatch: # Mantiene el botón manual y el disparo por API/a-Shell

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wyze-sdk garminconnect garth certifi

      - name: Run Script
        env:
          WYZE_EMAIL: ${{ secrets.WYZE_EMAIL }}
          WYZE_PASSWORD: ${{ secrets.WYZE_PASSWORD }}
          WYZE_KEY_ID: ${{ secrets.WYZE_KEY_ID }}
          WYZE_API_KEY: ${{ secrets.WYZE_API_KEY }}
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        run: python scale.py

      - name: Commit and Push Checksum
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Registramos el archivo de control para evitar duplicados
          git add cksum.txt
          # Guardamos los cambios en el repositorio [skip ci]
          git commit -m "Update weight checksum [skip ci]" || exit 0
          git push
